output:
  format: csv # csv or json
  csv:
    prefix: "ねぎや陵楓閣_"
    encoding: "utf-8-sig"
  local_output:
    enabled: true
    directory: processed-csv
  s3:
    enabled: true
    bucket_name: onsen-jasper-importer-prod-data-xxxx
    access_key_id: 'xxxxx'
    secret_access_key: 'xxxxx'
    file_name: 'pms-reservations/'
    region: "ap-northeast-1"

date_ranges:
  history:
    start_offset_days: -2
    end_offset_days: -2
  onhand:
    start_offset_days: -1
    end_offset_days: 178
  manual:
    enabled: false
    history:
      start: "2026-01-01"
      end: "2026-01-01"
    onhand:
      start: "2026-01-02"
      end: "2026-01-31"

datasets:
  reservations:
    primary_source: reservations
    merge_key: guest_id
    output_fields:
      - reservation_id
      - check_in_date
      - check_out_date
      - reserved_at
      - reservation_status
      - updated_at
      - number_of_adults
      - number_of_children
      - number_of_male
      - number_of_female
      - number_of_child_a
      - number_of_child_b
      - number_of_child_c
      - number_of_child_d
      - number_of_infants
      - total_amount
      - sales_office_company_name
      - package_plan_name
      - package_plan_code
      - external_confirmation_code
      - total_stay_count
      - guest_id
      - name_first
      - name_last
      - guest_name
      - phone_mobile
      - email
      - is_delivery_agreement
      - address
      - nationality
    computed_fields:
      guest_name:
        operation: concat
        fields:
          - name_last
          - name_first
        separator: " "
    sources:
      reservations:
        path: /reservations
        params:
          include_related_guest: 1
        date_params:
          start: check_in_date_from
          end: check_in_date_to
        field_paths:
          total_stay_count: related_guest.total_stay_count
          name_first: primary_guest.name_first
          name_last: primary_guest.name_last
          phone_mobile: primary_guest.phone_mobile
          email: primary_guest.email
          is_delivery_agreement: related_guest.is_delivery_agreement
          address: primary_guest.address
          nationality: related_guest.nationality
        fields:
        - reservation_id
        - check_in_date
        - check_out_date
        - reserved_at
        - reservation_status
        - updated_at
        - number_of_adults
        - number_of_children
        - number_of_male
        - number_of_female
        - number_of_child_a
        - number_of_child_b
        - number_of_child_c
        - number_of_child_d
        - number_of_infants
        - total_amount
        - sales_office_company_name
        - package_plan_name
        - package_plan_code
        - external_confirmation_code
        - total_stay_count
        - guest_id
        - name_first
        - name_last
        - phone_mobile
        - email
        - is_delivery_agreement
        - address
        - nationality

  sales:
    primary_source: sales
    merge_key: reservation_id
    output_fields:
      - reservation_id
      - sales_date
      - sales_department_code
      - sales_department_name
      - sales_subject_code
      - sales_subject_name
      - sales_sub_subject_code
      - sales_sub_subject_name
      - amount
      - amount_excluding_tax
      - consumption_tax
      - quantity
    computed_fields:
      consumption_tax:
        operation: subtract
        left: amount
        right: amount_excluding_tax
    sources:
      sales:
        path: /sales-details
        date_params:
          start: sales_date_from
          end: sales_date_to
        field_paths:
          reservation_id: reservation.reservation_id
          sales_department_code: sales_department.sales_department_code
          sales_department_name: sales_department.sales_department_name
          sales_subject_code: sales_subject.sales_subject_code
          sales_subject_name: sales_subject.sales_subject_name
          sales_sub_subject_code: sales_sub_subject.sales_subject_code
          sales_sub_subject_name: sales_sub_subject.sales_subject_name
        fields:
        - reservation_id
        - sales_date
        - sales_department_code
        - sales_department_name
        - sales_subject_code
        - sales_subject_name
        - sales_sub_subject_code
        - sales_sub_subject_name
        - amount
        - amount_excluding_tax
        - quantity

  rooms:
    primary_source: rooms
    merge_key: reservation_id
    output_fields:
      - reservation_id
      - room_usage_date
      - room_number
    sources:
      rooms:
        path: /reservations
        date_params:
          start: check_in_date_from
          end: check_in_date_to
        explode: assign_rooms
        field_paths:
          reservation_id: root.reservation_id
          room_usage_date: room_usage_start_date
          room_number: room.room_number|room_number|room.number
        fields:
          - reservation_id
          - room_usage_date
          - room_number
